export const productArray = [
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-gold-Recovered.png",
    id: "1",
    price: "89",
    size: "S",
    color:"Gold",
  },
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-gold-Recovered.png",
    id: "2",
    price: "89",
    size: "M",
    color:"Gold",
  },
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-gold-Recovered.png",
    id: "3",
    price: "89",
    size: "L",
    color:"Gold",
  },
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-green-Recovered.png",
    id: "4",
    price: "99",
    size: "S",
    color:"Green",
  },
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-green-Recovered.png",
    id: "5",
    price: "99",
    size: "M",
    color:"Green",
  },
  {
    name: " Hike Jacket",
    dicription: " a man hiking",
    image: "/images/rain/man-hiking-green-Recovered.png",
    id: "6",
    price: "99",
    size: "L",
    color:"Green",
  },
  {
    name: " Ski Jacket",
    dicription: " a person skiing",
    image: "/images/rain/skiing-Recovered.png",
    id: "7",
    price: "85",
    size: "S",
    color:"Red",
  },
  {
    name: " Ski Jacket",
    dicription: " a person skiing",
    image: "/images/rain/skiing-Recovered.png",
    id: "8",
    price: "85",
    size: "M",
    color:"Red",
  },
  {
    name: " Ski Jacket",
    dicription: " a person skiingt",
    image: "/images/rain/skiing-Recovered.png",
    id: "9",
    price: "85",
    size: "L",
    color:"Red",
  },
];